#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Sets up the production Supabase project and the GitHub environment secrets CI reads
# from it (issue #90). Run from anywhere in the repo: bash scripts/setup-supabase.sh
#
# Secrets go to the `preview` and `production` GitHub environments, never the repo, so
# the production database password only reaches jobs that run in `production`. Only
# non-secret values are saved to .env; a re-run asks for the secrets again, and a blank
# answer leaves what GitHub already has.

cd "$(git rev-parse --show-toplevel)"

# set_env_secret ENV NAME VALUE sets a secret on one GitHub environment. A blank VALUE
# skips it, so a re-run can leave an existing secret alone.
set_env_secret() {
  local env="$1" name="$2" value="$3"
  if [[ -z "$value" ]]; then
    note "left $name ($env) as it is"
    return
  fi
  if printf '%s' "$value" | gh secret set "$name" --env "$env" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name@$env")
    printf '  %s✓ set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$env"
  else
    SKIPPED+=("$name in $env (gh secret set $name --env $env)")
    warn "couldn't set $name in $env; set it later"
  fi
}

# expect_prefix VALUE PREFIX "what" warns when a pasted value doesn't look right.
expect_prefix() {
  [[ -z "$1" || "$1" == "$2"* ]] || warn "that doesn't start with $2; check it's the $3"
}

TOTAL_STAGES=7

banner "Supabase setup for CI (issue #90)"

stage "Check the organisation's plan"
say "Preview branches need the Pro plan or above; Free doesn't include branching."
say "Without them CI can't rehearse migrations or build PR previews (ADR 0009)."
open_url "https://supabase.com/dashboard"
step "Open the organisation the project will live in."
step "Check its plan under Billing, and upgrade to Pro if it's on Free."
note "Each preview branch is billed by the hour while it exists."
pause "Press Enter once the organisation is on Pro or above."

stage "Create the project"
open_url "https://supabase.com/dashboard/new/_"
step "Pick the organisation from the last stage."
step "Name the project, e.g. delivery-app."
step "Generate a strong database password and copy it before moving on."
step "Region: choose Southeast Asia (Singapore) itself, not the general APAC option,"
say "  which can land anywhere in Asia-Pacific."
step "Create the project and wait until the dashboard says it's ready."
note "Lost the password? Reset it later under Database → Settings."
ask_secret SUPABASE_DB_PASSWORD "Paste the database password:"

stage "Note the project ref"
say "The ref is the 20-letter id in the dashboard URL: .../dashboard/project/<ref>"
while :; do
  ask SUPABASE_PROJECT_ID "Paste the project ref:"
  [[ "$SUPABASE_PROJECT_ID" =~ ^[a-z0-9]{20}$ ]] && break
  warn "a ref is 20 lowercase letters or digits; try again"
done
SUPABASE_URL="https://$SUPABASE_PROJECT_ID.supabase.co"
write_env SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
write_env SUPABASE_URL "$SUPABASE_URL"

stage "Copy the publishable key"
say "The console's browser key. New projects have a publishable key in place of the"
say "old anon key; CI stores it as SUPABASE_ANON_KEY."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_ID/settings/api-keys"
step "Copy the publishable key (it starts sb_publishable_)."
warn "Never the secret key (sb_secret_): it bypasses row level security."
ask SUPABASE_ANON_KEY "Paste the publishable key:"
expect_prefix "$SUPABASE_ANON_KEY" sb_publishable_ "publishable key"

stage "Create an access token for CI"
say "CI uses it to find each PR's preview branch and to link the production migration."
open_url "https://supabase.com/dashboard/account/tokens"
step "Generate a new classic token named e.g. delivery-app CI."
step "Give it an expiry (a year at most) and note the date: CI breaks when it lapses."
note "A scoped token would be tighter, but which permissions CI needs is unconfirmed."
ask_secret SUPABASE_ACCESS_TOKEN "Paste the token:"
expect_prefix "$SUPABASE_ACCESS_TOKEN" sbp_ "access token"

stage "Write the GitHub environment secrets"
say "preview:    SUPABASE_ACCESS_TOKEN, SUPABASE_PROJECT_ID"
say "production: SUPABASE_ACCESS_TOKEN, SUPABASE_PROJECT_ID, SUPABASE_DB_PASSWORD,"
say "            SUPABASE_URL, SUPABASE_ANON_KEY"
note "Preview branches have their own database password, which CI reads from the"
note "Supabase API, so SUPABASE_PREVIEW_DB_PASSWORD is left unset."
if ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't logged in; run gh auth login, then re-run this wizard."
  SKIPPED+=("all GitHub secrets (gh not logged in)")
elif confirm "Write these, replacing any values already there?"; then
  for env in preview production; do
    set_env_secret "$env" SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
    set_env_secret "$env" SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
  done
  set_env_secret production SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
  set_env_secret production SUPABASE_URL "$SUPABASE_URL"
  set_env_secret production SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
else
  SKIPPED+=("all GitHub secrets (declined)")
fi
pause

stage "Connect the GitHub integration"
say "This is what creates a preview branch for each PR."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_ID/settings/integrations"
step "Under GitHub Integration, Authorize GitHub, then pick vgviscayno/delivery-app."
step "Working directory: .   (the folder that contains supabase/)"
step "Automatic branching: on."
step "Supabase changes only: on."
warn "Deploy to production: OFF. Migrations reach production only through the"
warn "Migrate production workflow (ADR 0009); on, a merge would migrate it."
step "Enable the integration."
pause "Press Enter once it's enabled."

finish
say "Next: add the Cloudflare secrets (#90), then re-run CI on a PR."
