#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Sets up the Cloudflare Pages project the console deploys to, and the GitHub
# environment values CI's `console` job reads (issue #90). Run from anywhere in the
# repo: bash scripts/setup-cloudflare.sh
#
# Values go to the `production` GitHub environment, like the Supabase ones: the console
# deploys from main only, pointed at production (ADR 0012). The API token is never
# saved to .env; a re-run asks for it again, and a blank answer leaves what GitHub
# already has.

cd "$(git rev-parse --show-toplevel)"

# On Windows, `bash` from PowerShell is WSL's, which finds the Windows pnpm but not the
# Node it needs. Git Bash sees both.
if ! command -v node >/dev/null 2>&1; then
  warn "node isn't on this shell's PATH, so wrangler can't run."
  note "On Windows, run it with Git Bash, not WSL:"
  note '  & "C:\Program Files\Git\bin\bash.exe" scripts/setup-cloudflare.sh'
  exit 1
fi

# Wrangler here acts as you, through its browser login. A token left in the environment
# would win over that login, and `wrangler login` refuses to run while one is set.
unset CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID

# wrangler runs the console's own copy, the one CI deploys with.
wrangler() { pnpm --filter @courier/console exec wrangler "$@"; }

# set_env_secret ENV NAME VALUE sets a secret on one GitHub environment. A blank VALUE
# skips it, so a re-run can leave an existing secret alone.
set_env_secret() {
  local env="$1" name="$2" value="$3"
  if [[ -z "$value" ]]; then
    note "left $name ($env) as it is"
    return
  fi
  if printf '%s' "$value" | gh secret set "$name" --env "$env" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name@$env")
    printf '  %s✓ set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$env"
  else
    SKIPPED+=("$name in $env (gh secret set $name --env $env)")
    warn "couldn't set $name in $env; set it later"
  fi
}

# set_env_var ENV NAME VALUE sets a (non-secret) variable on one GitHub environment.
set_env_var() {
  local env="$1" name="$2" value="$3"
  if gh variable set "$name" --env "$env" --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s variable %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$env"
  else
    SKIPPED+=("variable $name in $env (gh variable set $name --env $env)")
    warn "couldn't set variable $name in $env; set it later"
  fi
}

TOTAL_STAGES=5

banner "Cloudflare Pages setup for the console (issue #90)"

stage "Log wrangler in"
say "Wrangler creates the Pages project and reads the account ID. This login is for"
say "this machine only; CI gets its own API token in stage 4."
if wrangler whoami 2>/dev/null | grep -q "You are logged in"; then
  note "already logged in"
else
  step "A browser opens: log in to Cloudflare and click Allow."
  pause "Press Enter to open it"
  wrangler login || warn "login didn't finish; re-run this wizard to try again"
fi
pause

stage "Create the Pages project"
say "The console deploys here from main. The name becomes <name>.pages.dev."
[[ -n "$(_existing CLOUDFLARE_PAGES_PROJECT || true)" ]] || note "Suggested: courier-console"
while :; do
  ask CLOUDFLARE_PAGES_PROJECT "Project name:"
  [[ "$CLOUDFLARE_PAGES_PROJECT" =~ ^[a-z0-9][a-z0-9-]*$ ]] && break
  warn "use lowercase letters, digits and dashes; try again"
done
write_env CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
# --production-branch matches the --branch=main CI deploys with, so those deploys are
# production deploys, not previews.
if wrangler pages project list 2>/dev/null | grep -q "│ $CLOUDFLARE_PAGES_PROJECT "; then
  note "$CLOUDFLARE_PAGES_PROJECT already exists"
elif wrangler pages project create "$CLOUDFLARE_PAGES_PROJECT" --production-branch=main; then
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$CLOUDFLARE_PAGES_PROJECT"
else
  warn "create failed; fine if the project already exists (re-run), otherwise read the error above"
fi
pause

stage "Note the account ID"
say "Your account ID is in the table below (32 letters and digits)."
wrangler whoami || true
while :; do
  ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID:"
  [[ "$CLOUDFLARE_ACCOUNT_ID" =~ ^[a-f0-9]{32}$ ]] && break
  warn "an account ID is 32 lowercase hex characters; try again"
done
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

stage "Create an API token for CI"
say "The console job deploys with it. Give it Pages and nothing else."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click Create Token, then Get started next to Custom token."
step "Token name: delivery-app CI."
step "Permissions: Account → Cloudflare Pages → Edit. Add nothing else."
step "Account Resources: Include → your account."
step "Continue to summary → Create Token, and copy it: it's shown only once."
note "Input is hidden. In Git Bash, paste with Shift+Insert or right-click, not Ctrl+V."
# A token Cloudflare doesn't accept is asked for again, not written to GitHub, where it
# would only surface as a failed deploy. A blank answer skips it.
while :; do
  ask_secret CLOUDFLARE_API_TOKEN "Paste the token:"
  [[ -z "$CLOUDFLARE_API_TOKEN" ]] && break
  if curl -fsS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    https://api.cloudflare.com/client/v4/user/tokens/verify 2>/dev/null | grep -q '"status":"active"'; then
    printf '  %s✓ token is active%s\n' "$GREEN" "$RESET"
    break
  fi
  warn "Cloudflare doesn't accept that token; paste it again (blank to skip)"
done
pause

stage "Write the GitHub environment values"
say "production: secrets CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID"
say "            variable CLOUDFLARE_PAGES_PROJECT"
if ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't logged in; run gh auth login, then re-run this wizard."
  SKIPPED+=("all GitHub values (gh not logged in)")
elif confirm "Write these, replacing any values already there?"; then
  set_env_secret production CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  set_env_secret production CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
  set_env_var production CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
else
  SKIPPED+=("all GitHub values (declined)")
fi
pause

finish
say "Next: re-run the failed console job on main (gh run rerun <run-id> --failed)."
say "It deploys to https://$CLOUDFLARE_PAGES_PROJECT.pages.dev and, on the way, proves"
say "SUPABASE_URL and SUPABASE_ANON_KEY work."
