// Regenerates the Supabase types the domain package builds its hand-written types on.
//
// The generated file is checked in: a schema change and the TypeScript it breaks land
// in the same PR, the same rule the Kotlin side follows. CI regenerates and fails if
// the result differs from what is committed.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { repoRoot, supabase } from "./db.mjs";

const target = path.join(
  repoRoot,
  "packages",
  "domain",
  "src",
  "generated",
  "database.types.ts",
);

const result = supabase(["gen", "types", "typescript", "--local", "--schema", "public"], {
  stdio: ["inherit", "pipe", "inherit"],
});

const banner = [
  "// Generated by `pnpm db:types` from the local Supabase schema. Do not edit by hand.",
  "// Hand-written domain types live alongside this file and build on it.",
  "",
].join("\n");

await mkdir(path.dirname(target), { recursive: true });
await writeFile(target, banner + result.stdout, "utf8");

console.log(`Wrote ${path.relative(repoRoot, target)}`);
